server:
  port: 18080
#
#logging:
#  level:
#    root: DEBUG


spring:
  data:
    redis:
      host: 192.168.196.129
      port: 6379
      password: dong97
  application:
    name: eoffice-forum-gateway # 服务名称
  cloud:
    loadbalancer:
      nacos:
        enabled: false
    gateway:
      routes:
        - id: eoffice-forum-article1
          uri: lb://eoffice-forum-article
          predicates:
            - Path=/article/**

        - id: eoffice-forum-category1
          uri: lb://eoffice-forum-category
          predicates:
            - Path=/category/**

        - id: eoffice-forum-user1
          uri: lb://eoffice-forum-user
          predicates:
            - Path=/user/**

        - id: eoffice-forum-uploadFile1
          uri: lb://eoffice-forum-uploadFile
          predicates:
            - Path=/uploadFile/**

        - id: eoffice-forum-tools1
          uri: lb://eoffice-forum-tools
          predicates:
            - Path=/chat/**

        - id: eoffice-forum-userBehavior1
          uri: lb://eoffice-forum-userBehavior
          predicates:
            - Path=/userBehavior/**

        - id: eoffice-forum-userBehavior1
          uri: lb://eoffice-forum-userBehavior
          predicates:
            - Path=/userBehavior/**
