server:
  port: 18085

spring:
  application:
    name: eoffice-forum-tools


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://******:13306/forum_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: *****
  data:
    redis:
      host: *****
      port: 6379
      password: ******






